### ISSUE TITLE
Registered new user with empty password

### ISSUE THREAD

**Issue by rothenpieler** [wisebed/wisegui#106]
I just created a user with an empty password (accidentally) and see no possibilty to change or reset my password in the wisegui.

**Comment by danbim** [comment]
I didn't create a GUI link yet to the "change password" functionality. For now, please use this link http://portal.wisebed.itm.uni-luebeck.de/user_registration/#EMAIL/change_pwd, where EMAIL is your email address.

**Comment by danbim** [comment]
Fixed in https://github.com/itm/testbed-runtime/commit/5ef5bf5a51fc3529524d732b4a3c2b3b48bacded
