### ISSUE TITLE
Accessing to overview testbeds

### ISSUE THREAD

**Issue by ghilan20** [wisebed/wisegui#131]
When i tray  accessing to a overview testbeds using WiseGui http://wisebed.itm.uni-luebeck.de/  as you show in user guide the url doesn't work, do you have a new url for any testbed using  WiseGui? I want to do compare with my testbed.

**Comment by danbim** [comment]
Dear ghilan, unfortunately the testbed is not maintained anymore as the fundings projects were completed quite some while ago and in the meantime key researchers to run the testbed are not with the university anymore. Feel free  anyhow to setup your own testbeds with the our open source softwares!

**Comment by ghilan20** [comment]
Thanks for reply Mr. Bimschas


________________________________
