### ISSUE TITLE
Some "Scroll Down" Buttons do not work

### ISSUE THREAD

**Issue by master-lincoln** [wisebed/wisegui#17]
Some "Scroll Down" Buttons (and sometimes the Scrollbar) do not work. The "Scoll Up" Button does work, though. This affects e.g.:
- Time selection in "Make a reservation for Testbed"
- The "Filter Help Dialog" ("Advanced mode" example)

(Firefox 11.0, Win7)

**Comment by danbim** [comment]
Can you attach a screenshot of the buttons you mean? Can't reproduce it on the mac. The only buttons that I can think of are the ones from the windows scroll bar. But I wouldn't know a reason why they shouldn't work (except if it's a browser bug).

**Comment by master-lincoln** [comment]
Issue has been ported from rest-ws: https://github.com/wisebed/rest-ws/issues/84?source=cc
Original author: @rothenpieler
