### ISSUE TITLE
Pre-fill the experiment description text box

### ISSUE THREAD

**Issue by master-lincoln** [wisebed/wisegui#19]
The textbox of the experiment description in the reservation dialog should be pre-filled with a text like the username or the number of nodes or something more clever.

**Comment by danbim** [comment]
So. What description do you propose? I cannot think of one sensible.

**Comment by master-lincoln** [comment]
This issue was migrated from https://github.com/wisebed/rest-ws/issues/81
Original by @pfisterer

**Comment by danbim** [comment]
OK. Guess we can close it then...
