### ISSUE TITLE
Flash nodes control: file not updated if it changed on file system

### ISSUE THREAD

**Issue by master-lincoln** [wisebed/wisegui#2]
If you update the selected file contents by e.g., recompiling the WiseGui doesn't update the files bytes but flashes nodes with the old image. This is due to the fact that it reads the file contents when the file is selected and keeps it in the application as a byte-array.

**Comment by danbim** [comment]
Do you have any clue if the browser can actually work around this issue? I guess that when you provide a file selection button that opens a dialog the result of the action is not actually the path but the content of that file, isn't it?

**Comment by master-lincoln** [comment]
As far as I know there is currently no way to watch file changes from a browser.

**Comment by boldt** [comment]
http://stackoverflow.com/questions/4109276/how-to-detect-input-type-file-change-for-the-same-file

**Comment by master-lincoln** [comment]
Not exactly what we need. But a reload button to manually reupload the file could be added. But yeah, the [path is not accessible](http://stackoverflow.com/questions/4176377/how-to-get-the-full-path-of-the-file-from-a-file-input) and the file needs to be selected in the standard upload dialog again.

**Comment by danbim** [comment]
I don't want to force the user to reselect the file every time if it didn't change. It seems we'll have to live with that browser-caused issue for now.
