### ISSUE TITLE
Modal dialogs shown incorrect on small resolutions

### ISSUE THREAD

**Issue by master-lincoln** [wisebed/wisegui#25]
- http://paste.dennis-boldt.de/uni/002.png
- http://paste.dennis-boldt.de/uni/003.png

**Comment by danbim** [comment]
Just seen it on a monitor that was not able to display the "reserve" button in the reservation dialog. This is really high priority!!!

**Comment by boldt** [comment]
+1

**Comment by master-lincoln** [comment]
This is a general problem with bootstrap.
If it's just the reservation dialog I would suggest making the model positioned relatively, thus making the modal scroll with the rest of the page. I didn't find a way to apply this to all dialogs easily because placement would need to be done individually for each single modal.
_Edit_: Maybe the responsive version of the bootstrap css fixes that. I'll try that tomorrow.

**Comment by danbim** [comment]
I don't know about a "responsive version" but you could "easily" do it by attaching a listener to changes of the viewport size and dynamically resizing the dialog.

**Comment by pfisterer** [comment]
The problem persists. I just tried to reserve on my laptop and only could click on reserve after shrinking the zoom factor of the browser (CTRL + -)
