### ISSUE TITLE
Empty "Help" popup appears on http://wisebed.eu/site/testbed/

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#27]

**Comment by master-lincoln** [comment]
Which help popup do you mean? I was quickly clicking through the app and couldn't find it...

**Comment by danbim** [comment]
See attached Screenshot

On 24.08.12 11:56, Philipp Abraham wrote:

> Which help popup do you mean? I was quickly clicking through the app and
> couldn't find it...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wisebed/wisegui/issues/27#issuecomment-7997246.

## 

Daniel Bimschas, M.Sc.

UNIVERSITÄT ZU LÜBECK
    INSTITUT FÜR TELEMATIK

```
Ratzeburger Allee 160
23538 Lübeck

Tel +49 451 500 5387
Fax +49 451 500 5382
bimschas@itm.uni-luebeck.de

http://www.itm.uni-luebeck.de/users/bimschas
```

**Comment by danbim** [comment]
![](http://oi49.tinypic.com/2ymxedk.jpg)

**Comment by master-lincoln** [comment]
Could not reproduce here and you said it stopped. So I'll close for now...
