### ISSUE TITLE
Node outputs: table mode takes too much vertical space per message

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#33]
I think that the output of nodes should not take more space as it would take using a textarea, i.e. a single line of text. The horizontal lines defined in CSS can be removed as well.

**Comment by master-lincoln** [comment]
So you want to have a horizontal scrollbar if the message is not fitting in the output view?

**Comment by danbim** [comment]
_vertical space_ = line height

**Comment by master-lincoln** [comment]
Ok I'll reduce that. IMHO the horizontal separators are really helpful if you have a multiline message, e.g. you view a message in binary format.

**Comment by danbim** [comment]
You could be right there. But still, vertical space is used excessively currently
