### ISSUE TITLE
Node outputs: column headers inside scrollable area are rarely visible

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#34]
The column headers should be outside the scrollable area. If not possible, just remove them as the content is somewhat self-explaining.

**Comment by master-lincoln** [comment]
I have been looking into it and it's surprisingly complicated to make fixed headers. So I'd rather omit them completely.

**Comment by danbim** [comment]
Please do so ;-)

**Comment by boldt** [comment]
FYI: in the future, it will work: http://html5-demos.appspot.com/static/css/sticky.html

**Comment by master-lincoln** [comment]
oh cool...good to know. THX
