### ISSUE TITLE
Performance of hex/dec/binary output is very bad

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#39]

**Comment by danbim** [comment]
Alternative to performance-optimization of the JS code: provide several WebSockets at server side, one for each representation (Binary, Hex-Text, Dec-Text, Binary-Text, Ascii-Text).

**Comment by boldt** [comment]
Keep in mind: just 200 concurrent WebSocket-connections are possibile

**Comment by danbim** [comment]
Per server or user?

On 24.09.12 12:46, Dennis Boldt wrote:

> Keep in mind: just 200 concurrent WebSocket-connections are possibile
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wisebed/wisegui/issues/39#issuecomment-8813555.

## 

Daniel Bimschas, M.Sc.

UNIVERSITÄT ZU LÜBECK
    INSTITUT FÜR TELEMATIK

```
Ratzeburger Allee 160
23538 Lübeck

Tel +49 451 500 5387
Fax +49 451 500 5382
bimschas@itm.uni-luebeck.de

http://www.itm.uni-luebeck.de/users/bimschas
```

**Comment by boldt** [comment]
Per browser.

**Comment by danbim** [comment]
Then, we're fine with this ;-)

On 24.09.12 12:50, Dennis Boldt wrote:

> Per browser.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wisebed/wisegui/issues/39#issuecomment-8813814.

## 

Daniel Bimschas, M.Sc.

UNIVERSITÄT ZU LÜBECK
    INSTITUT FÜR TELEMATIK

```
Ratzeburger Allee 160
23538 Lübeck

Tel +49 451 500 5387
Fax +49 451 500 5382
bimschas@itm.uni-luebeck.de

http://www.itm.uni-luebeck.de/users/bimschas
```

**Comment by danbim** [comment]
Performance of String-manipulation seems to be OK. Using binary frames or some more efficient payload encoding will be topic of another issue.
