### ISSUE TITLE
Interactive "Shell-like" window for single nodes

### ISSUE THREAD

**Issue by pfisterer** [wisebed/wisegui#42]
Currently, there exists only a windows which displays all node outputs (and which may be filtered) and a dialog to send data to a single node.

The feature added by this ticket will be "shell-like" window for a single node where only the output of this node is displayed and the user can enter commands that will be sent to this node. 

The window shall be running in the background when "closed" keeping its state alive.

**Comment by danbim** [comment]
Grabbing this issue for myself...
