### ISSUE TITLE
Make Reservation view double scrolling, no button

### ISSUE THREAD

**Issue by MrMarvin** [wisebed/wisegui#44]
The make reservation view creates a list of nodes to select from, the element (`#WisebedTestbedMakeReservationList`) is scrollable. However it does not scroll far enough to see any button or whatsoever to submit the request.
Inspecting the DOM shows the `modal-footer` classed div with the buttons. They seem to be placed under (as in "on a lower z-axis value") the nodes list.

Happens in Chrome (some addons), FF (highly modified) and Safari (stock) on MacOSX.

**Comment by MrMarvin** [comment]
And by "Double Scrolling" I mean a browser window that is too small to show the whole page. Zomming out (or buying a larger monitor) solves this issue.

**Comment by master-lincoln** [comment]
This should have been fixed with 0dfddc69546014038e72b5bbe4b3161d8dabc5e7 .
I couldn't reproduce it with a quick test.
Where do you use wisegui? Maybe it's not up to date.
Try http://wisebed.github.com/wisegui for the most recent version.

**Comment by boldt** [comment]
You fix does not work. I can show the problem to you. I'm trying to fix it at the moment. If you're on the campus, do not hesitate to come my office to discuss the bug.

**Comment by boldt** [comment]
I just see in the source code, that the fix is not in the production version which is running on http://wisebed.github.com/wisegui
I added your fix manually, and it works.

**Comment by boldt** [comment]
Can you roll out the newest version. or shall I talk to Daniel?

**Comment by master-lincoln** [comment]
Sry I'm not on campus today. The URL you provided runs the gh-pages branch. https://github.com/wisebed/wisegui/tree/gh-pages which is up-to-date

**Comment by boldt** [comment]
Sry, C&P fail... I mean this version is not up2date: http://wisebed.itm.uni-luebeck.de/

**Comment by master-lincoln** [comment]
I can't update that one. You need to talk to Daniel for this.

**Comment by boldt** [comment]
It's on http://wisebed.itm.uni-luebeck.de now
