### ISSUE TITLE
Use Bootstrap Timepicker + Datepicker

### ISSUE THREAD

**Issue by boldt** [wisebed/wisegui#46]
Maybe we should use this bootstrap extention to select the time?
- http://jdewit.github.com/bootstrap-timepicker/

And the datepicker extention:
- https://github.com/eternicode/bootstrap-datepicker
- http://www.eyecon.ro/bootstrap-datepicker/

Or this to combine both:
- http://tarruda.github.com/bootstrap-datetimepicker/

**Comment by master-lincoln** [comment]
I would integrate that. We would just need to agree on one.
I like the combined one. But it might not be completely obvious how to reach the time selector for some people.
