### ISSUE TITLE
Load of remote experiment config fails

### ISSUE THREAD

**Issue by okleine** [wisebed/wisegui#48]
Try: http://media.itm.uni-luebeck.de/people/kleine/spitfire-wisebed/config.json and see what happens. Nothing at all...

**Comment by danbim** [comment]
Could you please post the error message (stack trace) from the browser debug view?

**Comment by okleine** [comment]
Sure. I hope thats what you requested:

Uncaught ReferenceError: that is not defined wisegui.js:3151
configCallback wisegui.js:3151
callCallback wisegui.js:346
callbackDone wisegui.js:362
fire jquery-1.7.1.js:1046
self.fireWith jquery-1.7.1.js:1164
done jquery-1.7.1.js:7399
callback

**Comment by danbim** [comment]
Yep, thanks. Bug fixed.

**Comment by okleine** [comment]
Very nice. That was fast! Thanks a lot!
