### ISSUE TITLE
Node selection for an experiment should stay persistent over page reloads

### ISSUE THREAD

**Issue by master-lincoln** [wisebed/wisegui#5]
If the user reloads a page (e.g., the experiment view) all his selections are lost because they are not persisted. It would be nice if the could be stored in the Browsers local storage (per experiment?) and restored when loading node selections.

**Comment by danbim** [comment]
Collected some experiences with the above commits. Would be much nicer though if we had a class (e.g., "StatefulControl") from which all the controls in the UI inherit so they can persist their state individually and load it when being loaded again.

**Comment by danbim** [comment]
Basically working...
