### ISSUE TITLE
Update position view on Google Maps according to updated WiseML coordinate type

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#62]
With the new WiseML coordinate type it is possible to specify outdoor coordinates using the all of the attributes below:

```
function Coordinate(latitude, longitude, x, y, z, phi, theta, rho) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.x = x;
    this.y = y;
    this.z = z;
    this.phi = phi;
    this.theta = theta;
    this.rho = rho;
}
```

So one can choose between using geographical, cartesian or spherical coordinates. The only possibility currently implemented is using geographical (lat, long) coordinates. TODO: implement conversions from cartesian and spherical to geographical coordinates.

**Comment by master-lincoln** [comment]
Possibly helpful: http://wiki.openstreetmap.org/wiki/Mercator#JavaScript

**Comment by danbim** [comment]
For now, we'll only go with support for lat/lng.
